[tool.semantic_release]
version_variables = ["setup.py:__version__"]
commit_message = "chore: update version to {version}"

[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.branches.pr]
match = "^(?!main).*"

[tool.semantic_release.commit_parser_options]
patch_tags = ["fix", "perf", "build"]
