services:
  flight-review:
    restart: unless-stopped
    volumes:
      - flight-review-data:/opt/service/data
      - shared-pyulog-db:/opt/service/data/shared-pyulog-db
      - ./config_user.ini:/opt/service/config_user.ini:ro
    ports:
      - 5006:5006
    environment:
      - USE_PROXY
      - DOMAIN

volumes:
  flight-review-data:
  shared-pyulog-db:
    external: true
