name: Tag deploy
on:
  push:
    tags:
      - "*"
      - "**"
jobs:
  tag_deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      tag: ${{ github.ref_name }}
      ref: ${{ github.sha }}
    secrets: inherit

  staging-deploy:
    needs: tag_deploy
    uses: ./.github/workflows/staging-deploy.yaml
    secrets: inherit
